### ISSUE TITLE
[question] does it output the (relative) file path ?

### ISSUE THREAD

**Issue by zilexa** [desbma/stfed#2]
Just wondering whether the actual path to the file + filename is available ? It's a bit unclear in SyncThing documentation:
https://docs.syncthing.net/events/itemfinished.html

Same question for (sub)folder completion.

**Comment by desbma** [comment]
If you are referring to the paths in the Syncthing events, from what I can see in my logs, it is always absolute.

**Comment by zilexa** [comment]
Thanks for your reply. I am not that technical, and was just hoping the paths would be there. I use Filerun (instead of the famous Nextcloud solution) and was hoping to find a way to inform Filerun of new files created by Syncthing, so that it will index those files, create thumbs etc, possibly adding them to some sort of Filerun queue to be processed.

But it is now up to the developer of Filerun to use your daemon to create a plugin of sorts that will support that. 

I haven't found other file managers that are fast, light etc. And I am not sure Nextcloud can be triggered for new files created by Syncthing. I know you should add your folders as external folders, if you use Nextcloud in combination with Syncthing, but haven't seen anywhere that it will be triggered automatically to index files and generate thumbs etc. So it would have the same issue as Filerun.
