### ISSUE TITLE
should look for .local/state/syncthing as well

### ISSUE THREAD

**Issue by mailinglists35** [desbma/stfed#4]
````
stat("/home/user/.config/syncthing/config.xml", 0x7ffcd9284540) = -1 ENOENT (No such file or directory)
stat("/etc/xdg/syncthing/config.xml", 0x7ffcd9284540) = -1 ENOENT (No such file or directory)
thread 'main' panicked at src/config.rs:62:14:
called `Result::unwrap()` on an `Err` value: Unable to guess stfed configuration field values from Synthing config, please write a config file
````

recently SyncThing changed xml location to `~/.local/state/syncthing`

**Comment by desbma** [comment]
I made a quick fix, can you try the [st-state-dir branch](https://github.com/desbma/stfed/tree/st-state-dir) to confirm it works?

**Comment by mailinglists35** [comment]
yes, thank you. I applied only that [commit](https://github.com/desbma/stfed/commit/7d2c5953ff77e3b801c7f3122d60b7097075fcda.patch) as a patch to previously cloned repo then commited locally in git, then cargo build again.
